name: Run LangChain Workflow on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-langchain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version, e.g. 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LangChain workflow script
        run: |
          python langchain_workflow.py
